service = "ZoteroSync"
endpoint = "https://api.zotero.org"
apikey = "XxuGdxZuXiB1epXH8B9XX2oR"
logfile = ""
#	"CRITICAL",
#	"ERROR",
#	"WARNING",
#	"NOTICE",
#	"INFO",
#	"DEBUG",
loglevel = "DEBUG"

#libraries = [1510019]
libraries = []
ignorelibraries = [2171465,2206003,2171463]
attachmentfolder = "//localhost/c$/temp/zotero"

[database]
#	servertype = "mysql"
#	dsn = "mediaserver:SWORDFISH@tcp(localhost:3306)/mediaserver?charset=utf8&sql_mode=ANSI_QUOTES"
	servertype = "postgres"
	dsn = "postgres://postgres:guslywyo@localhost/zotero"
	connection_max = 5000
	schema = "public"

